Repository JustinRafaelYahya/Mini-Project-JustinRafael-RidloGhifalry, pull requests merged in 2024-07, with the labels that each got.

#32 Feature/reset password
  apps/api/src/controllers/auth.controller.ts
  apps/api/src/routers/auth.router.ts
  apps/api/src/schemas/index.ts
  apps/web/src/actions/cookies.ts
  apps/web/src/api/auth/register/route.ts
  apps/web/src/api/auth/reset-password/route.ts
  apps/web/src/app/(protected)/reset-password/page.tsx
  apps/web/src/components/profile/ResetPasswordButton.tsx
  apps/web/src/components/profile/index.tsx
  apps/web/src/middleware.ts
Labels: enhancement

#36 Feature/dashboard
  apps/api/prisma/schema.prisma
  apps/api/src/app.ts
  apps/api/src/controllers/dashboard.controller.ts
  apps/api/src/routers/dashboard.router.ts
  apps/web/src/api/events/dashboard-chart/route.ts
  apps/web/src/app/(protected)/dashboard/_components/chart.tsx
  apps/web/src/app/(protected)/dashboard/_components/event-list.tsx
  apps/web/src/app/(protected)/dashboard/_components/life-time.tsx
  apps/web/src/app/(protected)/profile/[name]/_components/EventVisited/page.tsx
  apps/web/src/app/(protected)/profile/[name]/_components/MyEvent/page.tsx
  apps/web/src/app/(protected)/profile/[name]/_components/index.tsx
  apps/web/src/components/EventCards.tsx
  apps/web/src/middleware.ts
Labels: documentation

#41 Feature/otp code
  apps/api/package.json
  apps/api/prisma/migrations/20240729112938_otp_code/migration.sql
  apps/api/prisma/schema.prisma
  apps/api/src/controllers/auth.controller.ts
  apps/api/src/routers/auth.router.ts
  apps/api/src/schemas/index.ts
  apps/api/src/utils/nodemailer.ts
  apps/api/src/utils/send-email.ts
  apps/web/src/api/auth/verify-user/route.ts
  apps/web/src/app/(auth)/login/page.tsx
  apps/web/src/app/(auth)/register/page.tsx
  apps/web/src/app/(auth)/verify-user/page.tsx
  apps/web/src/components/auth/LoginMainPage.tsx
  apps/web/src/components/auth/SignupMainPage.tsx
  apps/web/src/components/auth/VerifyUserForm.tsx
  apps/web/src/middleware.ts
  package-lock.json
Labels: documentation

#42 fix: error message sign up
  apps/web/src/api/auth/login/route.ts
  apps/web/src/api/auth/register/route.ts
  apps/web/src/api/user/route.ts
  apps/web/src/components/auth/SignupMainPage.tsx
Labels: bug

#43 fix: type error when building
  apps/web/.eslintrc.json
  apps/web/src/api/user/route.ts
  apps/web/src/app/(protected)/profile/[name]/edit/_components/FormUpdate.tsx
  apps/web/src/app/api/getToken.ts
  apps/web/src/app/events/[id]/components/EventDetails.tsx
  apps/web/src/app/events/[id]/components/LikeButton.tsx
  apps/web/src/app/events/[id]/components/ReviewCard.tsx
  apps/web/src/app/events/[id]/edit/_components/FormUpdate.tsx
  apps/web/src/app/events/[id]/edit/page.tsx
  apps/web/src/components/Categories.tsx
  apps/web/src/components/LocationSelector.tsx
  apps/web/src/components/MainButton.tsx
  apps/web/src/components/MainPage.tsx
  apps/web/src/components/Navbar/Header.tsx
  apps/web/src/components/OriginalSearchbar.tsx
  apps/web/src/components/SearchBar.tsx
  apps/web/src/components/TimeFilterEvents.tsx
  apps/web/src/components/make-event/MakeEventForm.tsx
  apps/web/src/components/profile/LogoutButton.tsx
Labels: documentation

#44 Feature 1 rev: Removed event about in pop-up
  apps/api/src/controllers/event.controller.ts
  apps/api/src/controllers/review.controller.ts
  apps/api/src/controllers/transaction.controller.ts
  apps/api/src/routers/review.router.ts
  apps/api/src/routers/transaction.router.ts
  apps/web/package.json
  apps/web/src/api/events/reviews/route.ts
  apps/web/src/app/events/[id]/components/EventDetails.tsx
  apps/web/src/app/events/[id]/components/ReviewCard.tsx
  apps/web/src/components/MainPage.tsx
  apps/web/src/components/TimeFilterEvents.tsx
  apps/web/src/components/make-event/CategoriesDropDown.tsx
  apps/web/src/datas/CategoryDatas.tsx
  package-lock.json
Labels: enhancement
